"""POST /webhook — LemonSqueezy payment webhook with HMAC verification, AI report, email."""

import hashlib
import hmac as hmac_mod
import json
import logging
import re

import httpx
from fastapi import APIRouter, Request
from fastapi.responses import JSONResponse

from app.config import settings
from app.services.email_palette import email_palette
from app.services.email_sender import send_email

logger = logging.getLogger(__name__)

router = APIRouter()

OPENROUTER_URL = "https://openrouter.ai/api/v1/chat/completions"

_REPORT_PROMPT = """You are an elite landing page consultant who has optimized hundreds of high-converting pages. Provide a comprehensive, brutally honest analysis of this landing page.

Structure your report with these 10 sections:

1. **COPY TEARDOWN** — Analyze headline, subheadline, body copy, and CTAs. Are they clear, benefit-driven, and compelling?

2. **SEO AUDIT** — Check meta title, description, headings structure, alt text, and keyword usage.

3. **CRO OPPORTUNITIES** — Identify conversion blockers. Is the value prop clear above the fold? Any friction in the flow?

4. **DESIGN REVIEW** — Visual hierarchy, whitespace usage, color contrast, font choices, layout effectiveness.

5. **ACCESSIBILITY** — WCAG issues, color contrast, form labels, alt text, keyboard navigation hints.

6. **PERFORMANCE** — Image optimization, script loading, render-blocking resources, estimated impact.

7. **MOBILE UX** — Responsive design issues, touch targets, viewport settings, mobile-first considerations.

8. **TRUST SIGNALS** — Social proof, testimonials, guarantees, security badges, credibility indicators.

9. **COMPETITOR POSITIONING** — How well does the page differentiate? Is the unique value proposition clear?

10. **PRIORITIZED ACTION PLAN** — Top 10 changes ranked by impact and effort. Quick wins first.

For each section, give:
- Current state assessment (what's there now)
- Specific issues found
- Exact recommendations to fix them

Be specific. Reference actual text and elements from the page. No generic advice.

URL: {url}
HTML:
{truncated_html}"""


async def _fetch_page_html(url: str) -> str | None:
    """Fetch page HTML, truncate to 30k chars. Returns None on error."""
    try:
        async with httpx.AsyncClient(timeout=15.0) as client:
            resp = await client.get(
                url,
                headers={"User-Agent": "Mozilla/5.0 (compatible; alpo.ai/1.0)"},
                follow_redirects=True,
            )
            return resp.text[:30000]
    except Exception:
        logger.exception("Failed to fetch page for webhook report: %s", url)
        return None


async def _generate_report(url: str, html: str) -> str:
    """Call OpenRouter to generate a prose report. Returns error string on failure."""
    api_key = settings.openai_api_key
    if not api_key:
        return "Error: Server configuration issue."

    prompt = _REPORT_PROMPT.format(url=url, truncated_html=html)

    try:
        async with httpx.AsyncClient(timeout=60.0) as client:
            resp = await client.post(
                OPENROUTER_URL,
                headers={
                    "Authorization": f"Bearer {api_key}",
                    "Content-Type": "application/json",
                },
                json={
                    "model": "openai/gpt-5.4-nano",
                    "messages": [{"role": "user", "content": prompt}],
                    "temperature": 0.4,
                    "max_tokens": 4000,
                },
            )
            resp.raise_for_status()
            data = resp.json()
            return (
                data.get("choices", [{}])[0]
                .get("message", {})
                .get("content", "Report generation failed.")
            )
    except Exception:
        logger.exception("AI report generation failed")
        return "Error generating report. Our team has been notified."


def _build_webhook_email(url: str, report: str) -> str:
    """Simple wrapper email for the AI-generated prose report."""
    p = email_palette
    # Convert markdown bold to <strong>, newlines to <br>
    report_html = re.sub(r"\*\*(.*?)\*\*", r"<strong>\1</strong>", report)
    report_html = report_html.replace("\n", "<br>")

    return f"""\
<div style="font-family: system-ui, sans-serif; max-width: 680px; margin: 0 auto; padding: 40px 20px;">
  <h1 style="font-size: 24px; margin-bottom: 8px;">Your alpo.ai Report</h1>
  <p style="color: {p["textMuted"]}; margin-bottom: 32px;">Analysis for: <a href="{url}">{url}</a></p>
  <div style="white-space: pre-wrap; line-height: 1.6;">{report_html}</div>
  <hr style="margin: 40px 0; border: none; border-top: 1px solid {p["divider"]};">
  <p style="color: {p["textTertiary"]}; font-size: 12px;">Generated by alpo.ai \u2014 AI Landing Page Analyzer</p>
</div>"""


@router.post("/webhook")
async def webhook(request: Request):
    try:
        # Read raw body for HMAC verification
        raw_body = await request.body()
        secret = settings.lemonsqueezy_webhook_secret
        signature = request.headers.get("x-signature", "")

        # Constant-time HMAC comparison
        expected = hmac_mod.new(
            secret.encode("utf-8"), raw_body, hashlib.sha256
        ).hexdigest()
        if not hmac_mod.compare_digest(signature, expected):
            return JSONResponse(
                status_code=401, content={"error": "Invalid signature"}
            )

        body = json.loads(raw_body)

        # Only process order_created events
        event_name = body.get("meta", {}).get("event_name")
        if event_name != "order_created":
            return {"ok": True}

        # Extract email and URL
        email = (body.get("data", {}).get("attributes", {}).get("user_email") or "").strip()
        custom_data = body.get("meta", {}).get("custom_data", {}) or {}
        page_url = (custom_data.get("url") or "").strip()

        if not email or not page_url:
            logger.error("Missing email or URL in webhook: email=%s, url=%s", email, page_url)
            return JSONResponse(
                status_code=400, content={"error": "Missing data"}
            )

        # Generate full report
        html = await _fetch_page_html(page_url)
        if html is None:
            report = "Error: Could not fetch the provided URL."
        else:
            report = await _generate_report(page_url, html)

        # Send report email
        email_html = _build_webhook_email(page_url, report)
        send_email(
            from_addr="alpo.ai <report@alpo.com>",
            to=email,
            subject=f"Your alpo.ai Report: {page_url}",
            html=email_html,
        )

        return {"ok": True}
    except Exception:
        logger.exception("Webhook error")
        return JSONResponse(
            status_code=500, content={"error": "Webhook failed"}
        )
